#!/bin/bash

#PBS -l nodes=10:ppn=1
#PBS -m ae
#PBS -j oe
#PBS -A PCS0288

cd $PBS_O_WORKDIR
make all

> $PBS_O_WORKDIR/results.csv

for n in {1..10}
do
    mpiexec -n $n MPI >> $PBS_O_WORKDIR/results.csv
done

make clean